name: Main Terraform Trigger
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:
jobs:
  call-terraform-workflow:
    name: Call Terraform Workflow
    uses: ./.github/workflows/terraform.yml
    with:
      path: .
  call-checkov-workflow:
    name: Call Checkov Workflow
    uses: ./.github/workflows/checkov.yml
    with:
      path: .